# configs/storage/router.yaml
_target_: src.tools.storage.router.StorageRouter

routes:
  "s3://":
    _target_: src.tools.storage.s3.S3Storage
    bucket_name: "my-production-models"
    endpoint_url: ${oc.env:S3_ENDPOINT_URL, null}
    aws_access_key_id: ${oc.env:AWS_ACCESS_KEY_ID, null}
    aws_secret_access_key: ${oc.env:AWS_SECRET_ACCESS_KEY, null}

  "hf://":
    _target_: src.tools.storage.hf_hub.HFHubStorage
    repo_id: "твоя-организация/твоя-модель"
    token: ${oc.env:HF_TOKEN, null}
    repo_type: "model"

  "local://":
    _target_: src.tools.storage.local.LocalStorage
    base_dir: ${paths.model_dir}/prod_storage