# src/api/metrics.py
"""Метрики Prometheus для мониторинга API и модели (дашборды Grafana, алертинг)."""

from prometheus_client import Counter, Histogram


# Счётчик запросов к LLM
LLM_GENERATION_REQUESTS_TOTAL: Counter = Counter(
    "nlp_llm_generation_requests_total",
    "Total number of LLM generation requests",
    ["source", "status"],  # status: success | error
)

# Гистограмма времени генерации
LLM_GENERATION_TIME: Histogram = Histogram(
    "nlp_llm_generation_seconds",
    "Time spent generating text in model",
    ["source"],
    # Бакеты: 50ms–60s — типичный диапазон для LLM-инференса
    buckets=(0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0),
)

# Счётчик сгенерированных токенов
LLM_GENERATED_TOKENS_TOTAL: Counter = Counter(
    "nlp_llm_generated_tokens_total",
    "Total number of tokens generated by LLM",
    ["source"],
)
