# @package model

model_name: "DeepPavlov/rubert-base-cased"
is_causal_lm: False

builder:
  auto_model_class: "transformers.AutoModelForSequenceClassification"
  torch_dtype: "float32"

loss_fn:
  _target_: torch.nn.CrossEntropyLoss