# @package model

model_name: "meta-llama/Meta-Llama-3-8B"
is_causal_lm: True

# Теперь этот builder честно перезапишет и дополнит builder из дефолта!
builder:
  auto_model_class: "transformers.AutoModelForCausalLM"
  torch_dtype: "bfloat16"
  
  quantization_config:
    load_in_4bit: True
    bnb_4bit_compute_dtype: "bfloat16"
    bnb_4bit_use_double_quant: True
    bnb_4bit_quant_type: "nf4"

  peft_config:
      r: 16                     
      lora_alpha: 32            
      lora_dropout: 0.05
      bias: "none"
      task_type: "CAUSAL_LM"
      target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]