# @package model.architecture
model_name_or_path: "${paths.data_dir}/weights/my_local_merged_model" # Заглушка
mlflow_model_name: "LocalMerged_v1" # Имя без слэшей для Model Registry
auto_model_class: "transformers.AutoModelForCausalLM"
torch_dtype: "bfloat16"
attn_implementation: "flash_attention_2"
trust_remote_code: false