# @package model.architecture
model_name_or_path: "microsoft/Phi-4-mini-instruct"
mlflow_model_name: "Phi-4-mini-instruct"
auto_model_class: "transformers.AutoModelForCausalLM"
torch_dtype: "bfloat16"
attn_implementation: "sdpa"
trust_remote_code: false
rope_scaling: null