# @package model.architecture
model_name_or_path: "Qwen/Qwen2.5-1.5B"
mlflow_model_name: "Qwen2.5-1.5B"
auto_model_class: "transformers.AutoModelForCausalLM"
torch_dtype: "bfloat16"
attn_implementation: "flash_attention_2"
trust_remote_code: false