# @package model.architecture
model_name_or_path: "HuggingFaceM4/tiny-random-LlamaForCausalLM"
mlflow_model_name: "tiny-random-LlamaForCausalLM"
auto_model_class: "transformers.AutoModelForCausalLM"
torch_dtype: "bfloat16"
attn_implementation: "sdpa"
trust_remote_code: false