# configs/rag_pipeline/model/default.yaml

defaults:
  - architecture: test          # Тут будет лежать auto_model_class: "transformers.AutoModel"
  - pooling: mean                 # Наш новый компонент для RAG
  - tokenizer: default
  - quantization: none
  - modifiers/embedding_resize: default
  - modifiers/finetuning: lora
  - _self_

# Этот узел передается в instantiate() в scripts/train.py
builder:
  _target_: src.rag_pipeline.core.models.builder.HFModelBuilder
  _recursive_: false
  
  # Прокидываем необходимые параметры архитектуры
  model_name_or_path: ${rag_pipeline.model.architecture.model_name_or_path}
  auto_model_class: ${rag_pipeline.model.architecture.auto_model_class}
  cache_dir: ${paths.data_dir}/weights
  trust_remote_code: ${rag_pipeline.model.architecture.trust_remote_code}
  torch_dtype: ${rag_pipeline.model.architecture.torch_dtype}
  attn_implementation: ${rag_pipeline.model.architecture.attn_implementation}
  
  # Прокидываем конфигурации модификаторов и квантования
  quantization_config: ${rag_pipeline.model.quantization}
  modifiers: ${rag_pipeline.model.modifiers}

# Пулер будет инстанцироваться отдельно в train.py и передаваться в LightningModule
pooler:
  _target_: src.rag_pipeline.core.models.pooling.Pooler
  pooling_mode: ${rag_pipeline.model.pooling.pooling_mode}
  normalize: ${rag_pipeline.model.pooling.normalize}