# inference/generator/vllm.yaml
_target_: src.pipelines.decoder.inference.inference.LLMGenerationClient
_recursive_: false
api_base: ${oc.env:LLM_API_URL,http://localhost:8000/v1}
temperature: 0.7
max_tokens: 1024
max_concurrent_requests: 20