# helm/nlp-api-chart/values.yaml

app:
  name: nlp-template-api
  namespace: ml-pipelines

image:
  repository: my-company/nlp_template
  tag: api-latest

config:
  port: 8000
  mlflowTrackingUri: "http://mlflow-service:5000"
  modelName: "NlpTemplateModel"

resources:
  requests:
    cpu: "1"
    memory: "4Gi"
  limits:
    cpu: "2"
    memory: "6Gi" 
    gpu: "1"

storage:
  dataPvcName: pvc-data
  dataSize: 20Gi
  logsPvcName: logs-pvc
  logsSize: 10Gi
  modelsPvcName: pvc-models
  modelsSize: 30Gi
  # Добавлено хранилище для FAISS
  vectorDbPvcName: vector-db-pvc
  vectorDbSize: 20Gi

secrets:
  tgBotToken: "YOUR_TG_BOT_TOKEN"
  hfToken: "YOUR_HF_TOKEN"
  apiKey: "YOUR_API_KEY"
  kaggleUsername: "YOUR_KAGGLE_USERNAME"
  kaggleKey: "YOUR_KAGGLE_KEY"