# @package _global_
# configs/vector_db/hnsw.yaml

vector_db:
  # --- Параметры создания индекса ---
  _target_: src.vector_store.faiss_store.FAISSVectorStore
  embedding_dim: 1024
  index_type: "hnsw"
  m: 16
  ef_construction: 200
  ef_search: 50
  normalize_embeddings: true
  insert_batch_size: 10000
  filter_fetch_multiplier: 5
  filter_max_fetch_multiplier: 50

  # --- Параметры загрузки ---
  loader:
    _target_: src.vector_store.faiss_store.FAISSVectorStore.load
    embedding_dim: 1024
    index_type: "hnsw"
    m: 16
    ef_construction: 200
    ef_search: 50
    normalize_embeddings: true