# helm/decoder-api-chart/templates/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secrets
  namespace: {{ .Values.app.namespace }}
type: Opaque
stringData:
  TG_BOT_TOKEN: {{ .Values.secrets.tgBotToken | quote }}
  HF_TOKEN: {{ .Values.secrets.hfToken | quote }}
  WANDB_API_KEY: {{ .Values.secrets.wandbApiKey | quote }}
  API_KEY: {{ .Values.secrets.apiKey | quote }}
  KAGGLE_USERNAME: {{ .Values.secrets.kaggleUsername | quote }}
  KAGGLE_KEY: {{ .Values.secrets.kaggleKey | quote }}