# @package _global_
defaults:
  - system: default
  - model: eval_decoder
  - inference/generator: local
  - inference/cleaner: default
  - api/shared/server: default@api.server
  - api/shared/rate_limit: default@api.rate_limit
  - _self_
  - environments: prod_decoder

project_name: "nlp_project"
pipeline_name: "decoder_pipeline"

api:
  service_name: "decoder_api"
  server:
    title: "Decoder Generation API"
    description: "Генерация текста через локальную модель."