defaults:
  - _self_
  - architecture: bert_classifier

# --- Базовый скелет Токенизатора ---
tokenizer:
  _target_: src.core.models.tokenization.HFTokenizerBuilder
  # Имя модели прилетит из файла архитектуры при слиянии
  tokenizer_name: ${model.architecture.model_name}
  use_fast: True
  padding_side: "right"
  add_eos_token: False

# --- Базовый скелет Билдера Модели ---
builder:
  _target_: src.core.models.builder.HFModelBuilder
  model_name_or_path: ${model.architecture.model_name}
  cache_dir: "${paths.hf_cache_dir}"
  trust_remote_code: False
  # Fallback-значения (если архитектура их не перезапишет)
  auto_model_class: "transformers.AutoModel" 
  torch_dtype: "auto"

generation:
  _target_: src.core.models.generation.HFTextGenerator
  # model и tokenizer мы передадим из кода через instantiate
  generation_kwargs:
    max_new_tokens: 256
    temperature: 0.7
    top_p: 0.9
    do_sample: True
    repetition_penalty: 1.1

cleaner:
  _target_: src.core.models.parsers.ResponseCleaner
  strip_prompt: true
  remove_special_tokens: true
  remove_extra_spaces: true
  trim_incomplete_sentence: true