# @package model
defaults:
  - architecture: test
  - tokenizer: default
  - quantization: none
  - modifiers/embedding_resize: default
  - modifiers/finetuning: lora
  - _self_

# Этот узел передается в instantiate()
builder:
  _target_: src.core.models.builder.HFModelBuilder
  _recursive_: false
  
  # Прокидываем необходимые параметры
  model_name_or_path: ${model.architecture.model_name_or_path}
  auto_model_class: ${model.architecture.auto_model_class}
  cache_dir: ${paths.data_dir}/weights
  trust_remote_code: ${model.architecture.trust_remote_code}
  torch_dtype: ${model.architecture.torch_dtype}
  attn_implementation: ${model.architecture.attn_implementation}
  
  # Прокидываем конфигурации, собранные Hydra в корне узла model
  quantization_config: ${model.quantization}
  modifiers: ${model.modifiers}