# configs/model/train_rag.yaml
defaults:
  - builder: default
  - architecture: encoder/test
  - pooling: mean
  - quantization: none
  - tokenizer: default
  - modifiers/embedding_resize: default
  - modifiers/finetuning: lora_rag
  - _self_

use_manifest: true

# Переопределяем task_type для энкодера
modifiers:
  finetuning:
    peft_config:
      task_type: FEATURE_EXTRACTION