# configs/api/fastapi.yaml
defaults:
  - telegram: default
  - _self_


host: "0.0.0.0"
port: ${oc.env:API_PORT, 8000}
domain: "${oc.env:API_DOMAIN, 'http://localhost:8000'}"

title: "${oc.env:PROJECT_NAME,'Industrial NLP API'}"
description: "LLM backend with RAG and Hydra integration"
version: "${oc.env:PROJECT_VERSION,'0.1.0'}"

telegram_webhook:
  path: "/webhook/telegram"
  url: "${api.domain}${api.telegram_webhook.path}"

# Список доменов, которым разрешено делать запросы к нашему API из браузера
cors_origins:
  - "http://localhost:3000"     # Для локальной разработки фронтенда (React/Vue)
  - "http://localhost:8080"
  - "https://твоя-компания.com" # Продакшен домен