defaults:
  - architecture: test
  - tokenizer: default
  - quantization: none
  - modifiers/embedding_resize: default
  - modifiers/finetuning: lora
  - _self_

# Этот узел передается в instantiate()
builder:
  _target_: src.pipelines.base.core.models.builder.HFModelBuilder
  _recursive_: false
  
  # Прокидываем необходимые параметры
  model_name_or_path: ${decoder_pipeline.model.architecture.model_name_or_path}
  auto_model_class: ${decoder_pipeline.model.architecture.auto_model_class}
  cache_dir: ${paths.data_dir}/weights
  trust_remote_code: ${decoder_pipeline.model.architecture.trust_remote_code}
  torch_dtype: ${decoder_pipeline.model.architecture.torch_dtype}
  attn_implementation: ${decoder_pipeline.model.architecture.attn_implementation}
  
  # Прокидываем конфигурации, собранные Hydra в корне узла model
  quantization_config: ${decoder_pipeline.model.quantization}
  modifiers: ${decoder_pipeline.model.modifiers}