# configs/paths/default.yaml
root_dir: "."

data_dir:           "${paths.root_dir}/data/${pipeline_name}"
hf_cache_dir:       "${paths.root_dir}/data/cache/hf_models"   # общий, без pipeline_name
processed_data_dir: "${paths.data_dir}/processed"

log_dir:    "${paths.root_dir}/logs/${pipeline_name}"
mlflow_bd_dir: "${paths.root_dir}/logs" #менять вместе с лог дир(хардкор)
output_dir: "${paths.root_dir}/outputs/${pipeline_name}"
model_dir:  "${paths.root_dir}/models/${pipeline_name}"