defaults:
  - system: default  # Базовые настройки MLflow, логгеров, стораджа
  - model: train_rag
  - _self_

# Этот параметр мы будем передавать при запуске
project_name: "nlp_project"
pipeline_name: rag_pipeline
# Динамические пути, зависящие от pipeline_name
manifest:
  uri: local://manifests/${pipeline_name}_manifest.json