defaults:
  - system: default  # Базовые настройки MLflow, логгеров, стораджа
  - model: train_rag
  - _self_

project_name: "nlp_project"

# pipeline_name передаётся через override при запуске:
#   python -m src.tools.promote pipeline_name=rag_pipeline
#   python -m src.tools.promote pipeline_name=decoder_pipeline
pipeline_name: rag_pipeline