# src/api/metrics.py
"""Определение метрик Prometheus для мониторинга API и модели.

Используется для дашбордов Grafana и алертинга.
"""

from prometheus_client import Counter, Histogram


# Счетчик общего числа запросов к LLM
LLM_GENERATION_REQUESTS_TOTAL: Counter = Counter(
    "nlp_llm_generation_requests_total",
    "Total number of LLM generation requests",
    ["source"],
)

# Гистограмма времени генерации (latency)
LLM_GENERATION_TIME: Histogram = Histogram(
    "nlp_llm_generation_seconds", "Time spent generating text in model", ["source"]
)

# Счетчик сгенерированных токенов (для оценки нагрузки и производительности)
LLM_GENERATED_TOKENS_TOTAL: Counter = Counter(
    "nlp_llm_generated_tokens_total",
    "Total number of tokens generated by LLM",
    ["source"],
)
