_target_: src.pipelines.base.core.models.builder.HFModelBuilder
model_name_or_path: ???
auto_model_class: transformers.AutoModel
cache_dir: ${system.paths.hf_cache_dir}
trust_remote_code: true
torch_dtype: bfloat16
attn_implementation: flash_attention_2
device_map: auto_cuda
rope_scaling: null
quantization_config: ${model.quantization.quantization_config}
modifiers: ${model.modifiers}