# configs/storage/source/local.yaml
_target_: src.tools.storage.local.LocalStorage
base_dir: "${oc.env:PROJECT_ROOT, C:/Users/Maxim/nlptemplate_decoder_rag}/prod_storage" #тонкое место лучше дублировать из .env 
uri_prefix: "local://"